---
- hosts: 192.168.1.41
  become: true
  become_method: sudo
  tasks:
    - name: Stat/Stop apache service
      shell: |
          service apache2 start > /dev/null
          service apache2 status 2>&1 | tee /tmp/out.txt > /dev/null
          ./test.sh          
      ignore_errors: yes
      register: command_result
    - debug: msg={{ command_result.stdout }}


# - hosts: localhost
#   become: true
#   become_method: sudo
#   tasks:
#     - name: Stat/Stop apache service
#       shell: service apache2 start
#       shell: service apache2 status 2>&1 | tee /tmp/out.txt
#       shell: ./test.sh
#       ignore_errors: yes
#       register: command_result
#     - debug: msg={{ command_result.stdout }}



# - hosts: localhost
#   tasks:
#     - name: Checking apache status
#       shell: service apache2 status 2>&1 | tee /tmp/out.txt | ./test.sh
#       ignore_errors: yes
#       register: stat_result
#     - debug: msg={{ stat_result.stdout }}
# - hosts: localhost
#   tasks:
#     - name: Status
#       shell: ./test.sh
#       ignore_errors: yes
#       register: out_result
#     - debug: msg={{ out_result.stdout }}
# - hosts: localhost
#   tasks:
#     - name: Status
#       shell: sed '6,$d' /tmp/out.txt | sed '1,4d'
#       ignore_errors: yes
#       register: out_result
#     - debug: msg={{ out_result.stdout }}